DROP TABLE IF EXISTS BRANCH CASCADE;
DROP TABLE IF EXISTS BRANCH_PHONE CASCADE;
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS POSITION CASCADE;
DROP TABLE IF EXISTS EMPLOYEE_POSITION CASCADE;
DROP TABLE IF EXISTS CLIENT CASCADE;
DROP TABLE IF EXISTS CLIENT_ADDRESS CASCADE;
DROP TABLE IF EXISTS "ORDER" CASCADE;
