---- BRANCH
ALTER TABLE BRANCH ADD PRIMARY KEY(BRANCH_ID);
----

---- BRANCH_PHONE
ALTER TABLE BRANCH_PHONE ADD PRIMARY KEY(PHONE);
ALTER TABLE BRANCH_PHONE ADD FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE;
----

---- EMPLOYEE
ALTER TABLE EMPLOYEE ADD PRIMARY KEY(EMPLOYEE_ID);
-- we don't allow firing boss before regrouping his inferiors...
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(SUPERIOR_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE RESTRICT;
-- ...similarily we don't allow removing a company branch before firing or regrouping employees
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE RESTRICT;
----

---- POSITION
ALTER TABLE POSITION ADD PRIMARY KEY(POSITION_ID);
-- check minimum wage constraint
ALTER TABLE POSITION ADD CHECK(BASE_WAGE > 6.06);
----

---- EMPLOYEE_POSITION
ALTER TABLE EMPLOYEE_POSITION ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE;
ALTER TABLE EMPLOYEE_POSITION ADD FOREIGN KEY (POSITION_ID) REFERENCES POSITION(POSITION_ID) ON DELETE RESTRICT;
----

---- CLIENT
ALTER TABLE CLIENT ADD PRIMARY KEY(CLIENT_ID);
ALTER TABLE CLIENT_ADDRESS ADD PRIMARY KEY(CLIENT_ADDRESS_ID);
ALTER TABLE CLIENT ADD FOREIGN KEY(DEFAULT_SHIPMENT_ADDRESS_ID) REFERENCES CLIENT_ADDRESS(CLIENT_ADDRESS_ID);
ALTER TABLE CLIENT ADD FOREIGN KEY(DEFAULT_BILLING_ADDRESS_ID) REFERENCES CLIENT_ADDRESS(CLIENT_ADDRESS_ID);
----

---- CLIENT_ADDRESS
ALTER TABLE CLIENT_ADDRESS ADD FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID);
----

---- ORDER
ALTER TABLE "ORDER" ADD PRIMARY KEY(ORDER_ID);
ALTER TABLE "ORDER" ADD FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID);
ALTER TABLE "ORDER" ADD FOREIGN KEY(SHIPMENT_ADDRESS_ID) REFERENCES CLIENT_ADDRESS(CLIENT_ADDRESS_ID);
ALTER TABLE "ORDER" ADD FOREIGN KEY(BILLING_ADDRESS_ID) REFERENCES CLIENT_ADDRESS(CLIENT_ADDRESS_ID);
----
